// 当前规则文件用于测试 auto-focus 属性（需要配合 agenda-group 属性）
package test.attributesautofocus

// 第一个规则
rule "rule_autofocus_1"
    agenda-group "agenda_group_1" // agenda-group属性为议程分组，只有获得焦点的组中的规则才可以触发
    when
    then
        System.out.println("规则：rule_autofocus_1触发了...");
end

// 第二个规则
rule "rule_autofocus_2"
    agenda-group "agenda_group_1"
    when
    then
        System.out.println("规则：rule_autofocus_2触发了...");
end

// 第三个规则
rule "rule_autofocus_3"
    agenda-group "agenda_group_2"
    auto-focus true // auto-focus 属性用于指定当前所属组自动获取焦点
    when
    then
        System.out.println("规则：rule_autofocus_3触发了...");
end

// 第四个规则
rule "rule_autofocus_4"
    agenda-group "agenda_group_2"
    // 如果同一个 agenda-group 议程组中某个规则设置 kauto-focus 属性为 true，则其他的规则均为自动获取焦点
    auto-focus false
    when
    then
        System.out.println("规则：rule_autofocus_4触发了...");
end