// 当前规则文件用于测试LHS部分---extends
package test.lhsextends
import com.moon.drools.entity.Student

// 编写规则，演示extends关键字实现规则的条件部分继承
rule "rule_lhs_extends_1"
    when
        Student(age > 10)
    then
        System.out.println("规则：rule_lhs_extends_1 触发了...");
end

// 编写规则，演示extends关键字实现规则的条件部分继承
rule "rule_lhs_extends_2" extends "rule_lhs_extends_1"
    when
        /*
            此处的条件虽然只写了一个，但是从上面的规则继承了一个条件，
            所以当前规则存在两个条件，即Student(age < 20)和Student(age > 10)
        */
        Student(age < 20)
    then
        System.out.println("规则：rule_lhs_extends_2 触发了...");
end