// 当前规则文件用于测试RHS部分drools对象的相关方法
package test.rhsdrools
import org.drools.core.WorkingMemory

rule "rule_rhs_1"
    when
    then
        System.out.println("规则：rule_rhs_1 触发了...");
        // getWorkingMemory 方法用于获得工作内存对象，本质上是一个会话对象
        WorkingMemory workingMemory = drools.getWorkingMemory();
        System.out.println(workingMemory);
        // getRule 方法用于获得当前规则对象
        org.drools.core.definitions.rule.impl.RuleImpl rule = drools.getRule();
        System.out.println(rule);
        System.out.println(rule.getAutoFocus());
        System.out.println(rule.getId());
        System.out.println(rule.getDateExpires());
        // halt方法，用于终止后面所有规则的执行
        drools.halt();
end

rule "rule_rhs_2"
    when
    then
        System.out.println("规则：rule_rhs_2 触发了...");
end